### ISSUE TITLE
Ensure that all documents smartPublished from server is received by client

### ISSUE THREAD

**Issue by joboyx** [yeputons/meteor-smart-publish#14]
I also encountered documents that were missing. I'm sure that the document was smartPublished from server. But the client did not receive it. I checked the documents via Mongol tool.

I'm not 100% sure that this is related to smartPublish API. But since I also encountered documents that was not received by client in correct order, maybe this is related.

----

Here's my code and logs produced from server side:
```javascript
// Publications
Meteor.smartPublish("allitems", function (seed, limit) {
    console.log("### publish(" + seed + ", " + limit + ")");
    // return data with limit for infinite scrolling
    var items = Items.find({});
    var docCount = items.count();
    var itemsArray = items.fetch();
    var cursorArray = [];

    var seedRandom = Meteor.npmRequire('seedrandom');
    seedRandom(seed, {global: true});

    for(var idx, i = 0; i < limit; i++) {
        idx = Math.floor(Math.random() * docCount);
        console.log("### publish::Math.random() [" + (i+1) + "][" + itemsArray[idx]._id + "][" + idx + "]");
        cursorArray.push(
            Items.find({_id: itemsArray[idx]._id}, {limit: 1})
        );
    }

    return cursorArray;
});
```

As you can see from this logs from server, this document was not received by the client:

```I20150512-01:40:12.941(8)? ### publish::Math.random() [14][tdR7DGk3RggHiuX7G][685]```

```
I20150512-01:40:08.673(8)? ### publish(zzurkngpZkkJXrpaS, 10)
I20150512-01:40:08.686(8)? ### publish::Math.random() [1][rPFAPosdZXJZqSHCW][699]
I20150512-01:40:08.686(8)? ### publish::Math.random() [2][BWQdpx8YoQ2GJrATT][89]
I20150512-01:40:08.687(8)? ### publish::Math.random() [3][vDutaad3zEHcjSjWA][541]
I20150512-01:40:08.690(8)? ### publish::Math.random() [4][WMuCyqJBpvz9XNgn6][548]
I20150512-01:40:08.690(8)? ### publish::Math.random() [5][J69Xg8sTv3zbG8GYA][803]
I20150512-01:40:08.690(8)? ### publish::Math.random() [6][Bw2WSHu5y3KTLF94b][466]
I20150512-01:40:08.690(8)? ### publish::Math.random() [7][hL94tCLDFsxf39Ge3][457]
I20150512-01:40:08.690(8)? ### publish::Math.random() [8][bfAYhYN6h5M9fiYo3][632]
I20150512-01:40:08.691(8)? ### publish::Math.random() [9][4yFvTAJk7zj8qwDBn][192]
I20150512-01:40:08.691(8)? ### publish::Math.random() [10][AweG3rKyszix3cWXk][110]
I20150512-01:40:12.916(8)? ### publish(zzurkngpZkkJXrpaS, 20)
I20150512-01:40:12.938(8)? ### publish::Math.random() [1][rPFAPosdZXJZqSHCW][699]
I20150512-01:40:12.939(8)? ### publish::Math.random() [2][BWQdpx8YoQ2GJrATT][89]
I20150512-01:40:12.939(8)? ### publish::Math.random() [3][vDutaad3zEHcjSjWA][541]
I20150512-01:40:12.939(8)? ### publish::Math.random() [4][WMuCyqJBpvz9XNgn6][548]
I20150512-01:40:12.939(8)? ### publish::Math.random() [5][J69Xg8sTv3zbG8GYA][803]
I20150512-01:40:12.939(8)? ### publish::Math.random() [6][Bw2WSHu5y3KTLF94b][466]
I20150512-01:40:12.940(8)? ### publish::Math.random() [7][hL94tCLDFsxf39Ge3][457]
I20150512-01:40:12.941(8)? ### publish::Math.random() [8][bfAYhYN6h5M9fiYo3][632]
I20150512-01:40:12.941(8)? ### publish::Math.random() [9][4yFvTAJk7zj8qwDBn][192]
I20150512-01:40:12.941(8)? ### publish::Math.random() [10][AweG3rKyszix3cWXk][110]
I20150512-01:40:12.941(8)? ### publish::Math.random() [11][XQ2AhMnqrPngpST57][178]
I20150512-01:40:12.941(8)? ### publish::Math.random() [12][TedPF9Pxifsf3h3kQ][557]
I20150512-01:40:12.941(8)? ### publish::Math.random() [13][4yFvTAJk7zj8qwDBn][192]
I20150512-01:40:12.941(8)? ### publish::Math.random() [14][tdR7DGk3RggHiuX7G][685]
I20150512-01:40:12.942(8)? ### publish::Math.random() [15][vJWa9PPwMarApcxs9][813]
I20150512-01:40:12.942(8)? ### publish::Math.random() [16][ZjKXGE4kvdaewE3NP][684]
I20150512-01:40:12.942(8)? ### publish::Math.random() [17][symshYjbCmp9y3BXm][421]
I20150512-01:40:12.942(8)? ### publish::Math.random() [18][NXqpkFLbaPZecikYu][839]
I20150512-01:40:12.942(8)? ### publish::Math.random() [19][bXgg5nNkqRvh7TwAo][535]
I20150512-01:40:12.942(8)? ### publish::Math.random() [20][TJXiWe3xF4tcqACzt][84]
```

**Comment by joboyx** [comment]
@yeputons I checked your code here: http://pastebin.com/KF6b29rv. We almost have the same code on server and client except for the count session variable.

Is the ```limit``` parameter of the smartPublish's function callback always 0?

Try doing an event that will increment the ```Session.get('count')```. Say increment by 10 (10, 20, 30, 40...). Then check in the browser if the Items.find({}).count() is the equal to the count session variable.

The issue happens after several update of that ```Session.get('count')```

**Comment by yeputons** [comment]
@joboyx I've tried it like this: http://pastebin.com/Y12nhfzL . Actually, `Items.find({}).count()` should not be equal to the limit, because my code was lucky enough to select some elements twice. So I've added extra collection which contains one value - number of _distinct_ elements published by server. This is smaller than the limit, but it is correct. I assume it's not your case, because all objects in your log example are distinct. Would you mind checking that it's not the case?

You can either count distinct objects by yourself or just replace smart publishing with the following snippet:
~~~~
Meteor.publish("allitems", function (seed, limit) {
  // ...
  var ids = [];
  for(var idx, i = 0; i < limit; i++) {
    idx = Math.floor(Math.random() * docCount);
    ids.append(itemsArray[idx]._id];
  }
  return Items.find({_id: {$in: ids}});
});
~~~~
Please let me know whether behavior of smart publish and that snippet differ in your case.

**Comment by joboyx** [comment]
So I tried not to use smartPublish and use the ```$in``` notation of MongoDB instead.

Still same behavior, the issue still occurs. So definitely this is not related with your package. You can close this ticket now.

And I would never know that I really don't need your package without your help. ;)
Thanks!
