### ISSUE TITLE
Set the website of this GitHub repo to the Atmopshere package

### ISSUE THREAD

**Issue by dandv** [yeputons/meteor-smart-publish#15]
Example:

[![Adding GitHub repo URL](https://cloud.githubusercontent.com/assets/33569/6536430/76a7d88e-c402-11e4-8883-6ab2c7b8c30a.png)](https://github.com/dandv/meteor-webix)

Also rm mrt from the README please :)

**Comment by yeputons** [comment]
@dandv Thank you for the idea.

What do you mean by 'rm mrt from the README'? `mrt:` prefix for package name is a required prefix, isn't it?

**Comment by dandv** [comment]
Nevermind, looks like the package is under the mrt namespace, and it's impossible to transfer it under `yeputons:`.
