### ISSUE TITLE
bugs after update to meteor 1.2.0.1

### ISSUE THREAD

**Issue by h4de5** [yeputons/meteor-smart-publish#16]
I got the following error messages when working the first time with this package:
```
meteor smart publish ... Random is not defined
and
meteor smart publish ... EJSON is not defined
```
to make it work again in Meteor 1.2.0.1 you may need to add to more packages:

https://atmospherejs.com/meteor/random
```meteor add random```

https://atmospherejs.com/meteor/ejson
```meteor add ejson```

**Comment by yeputons** [comment]
@h4de5 Did that resolve the issue for you?

**Comment by h4de5** [comment]
seems to work fine. thanks for the fix.
