### ISSUE TITLE
Compatibility with added/changed/removed in publish

### ISSUE THREAD

**Issue by steph643** [yeputons/meteor-smart-publish#9]
As you know, there are two methods to implement a publish function:
1. By returning a cursor (or an array of cursors)
2. By using `this.added()` / `this.changed()` / `this.removed()`, usually from `cursor.observeChanges()` callbacks

Let's consider these three use cases for method 2:
a. You want to add a field to a document before publication
b. You want to remove a field from a document before publication
c. You want to do both, for example to combine several secret fields into one public field

Does *meteor-smart-publish* allow for these three use cases?

**Comment by steph643** [comment]
See the [same question in publish-composite](https://github.com/englue/meteor-publish-composite/issues/28).

**Comment by yeputons** [comment]
@steph643 It's partially closed: you can use these three callbacks in top-level publish function, you may take a look at `issue-9` branch.

I'll get back on this in a day or two.

**Comment by yeputons** [comment]
Just for me: do not forget about documenation and examples.

**Comment by yeputons** [comment]
@steph643 Would you mind updating to the last version - v0.2.0 and testing it?

**Comment by yeputons** [comment]
@steph643 feel free to re-open this issue or create a new one in case of any problems

**Comment by steph643** [comment]
@yeputons, sorry I had no time trying this.
